services:
  postgres:
    image: postgres:18
    container_name: dulutheats_postgres
    restart: always
    env_file:
      - ../backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis:7-alpine
    container_name: dulutheats_redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
volumes:
  postgres_data: